name: Python Scripts

# Controls when the action will run. 
on:
  schedule:
  - cron: "30 17 * * *" # UTC time (-1 en hiver et -2 en été)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pipenv install
        
    - name: Données Vaccin France
      run: |
        pipenv run python src/script.py
    - uses: stefanzweifel/git-auto-commit-action@v4
    
